# Generated by Django 3.0.2 on 2020-02-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('songfile', models.FileField(upload_to='')),
                ('duration', models.FloatField()),
            ],
        ),
    ]
