# Generated by Django 3.0.4 on 2020-03-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howsthexp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(max_length=100)),
                ('ln', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('ph_no', models.CharField(max_length=10, unique=True)),
                ('username', models.CharField(max_length=8, unique=True)),
                ('password', models.CharField(default='', max_length=5000)),
            ],
        ),
    ]
