# Generated by Django 3.0.4 on 2020-03-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howsthexp', '0002_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=8, unique=True)),
                ('password', models.CharField(default='', max_length=5000)),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
